apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ui-ingress
  namespace: exchange
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "www.example.com" # or "*" for all
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS" # or "*" for all
    nginx.ingress.kubernetes.io/cors-allow-headers: "apikey,apikey-signature"
spec:
  rules:
    - host: ui-dev.investbit.eu
      http:
        paths:
          - path: /
            backend:
              serviceName: exchange-ui
              servicePort: 80
