apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: weave-scope
  namespace: weave
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - host: example.com
    http:
      paths:
        - path: /api/.*
          backend:
            serviceName: weave-scope-app
            servicePort: 80
        - path: /private/.*
          backend:
            serviceName: default-backend
            servicePort: 80
